// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZWD6ulS85_ZWnDXljgmPORmdnwTAClOQ',
    appId: '1:421662211826:web:594c9124ca1dd1d4e15a6b',
    messagingSenderId: '421662211826',
    projectId: 'akili-dc22e',
    authDomain: 'akili-dc22e.firebaseapp.com',
    storageBucket: 'akili-dc22e.firebasestorage.app',
    measurementId: 'G-8V4X8P4B4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_6zdv34jM4WnGV3T1TcPZgGjPxIaVaCE',
    appId: '1:421662211826:android:cbaf2db7681abb36e15a6b',
    messagingSenderId: '421662211826',
    projectId: 'akili-dc22e',
    storageBucket: 'akili-dc22e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5AhFIhdYi1PoqAdM5LsV5nOn40gcmKFs',
    appId: '1:421662211826:ios:398b89b89bf80003e15a6b',
    messagingSenderId: '421662211826',
    projectId: 'akili-dc22e',
    storageBucket: 'akili-dc22e.firebasestorage.app',
    iosBundleId: 'rw.akili.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5AhFIhdYi1PoqAdM5LsV5nOn40gcmKFs',
    appId: '1:421662211826:ios:398b89b89bf80003e15a6b',
    messagingSenderId: '421662211826',
    projectId: 'akili-dc22e',
    storageBucket: 'akili-dc22e.firebasestorage.app',
    iosBundleId: 'rw.akili.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZWD6ulS85_ZWnDXljgmPORmdnwTAClOQ',
    appId: '1:421662211826:web:a7f6e27b886582d2e15a6b',
    messagingSenderId: '421662211826',
    projectId: 'akili-dc22e',
    authDomain: 'akili-dc22e.firebaseapp.com',
    storageBucket: 'akili-dc22e.firebasestorage.app',
    measurementId: 'G-WNM2P1BWB5',
  );
}
